services:
  client:
    build:
      context: ./drawing-board-client
      dockerfile: ./Dockerfile.dev
    container_name: client
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_SERVER_URL: ${VITE_SERVER_URL}
    volumes:
      - ./drawing-board-client:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - drawingboard_devnet
    restart: always

  server:
    build:
      context: ./drawing-board-server
      dockerfile: ./Dockerfile.dev
    container_name: server
    ports:
      - "3000:3000"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}

      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}

      CLIENT_URL: ${CLIENT_URL}
      DATABASE_URL: postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_NAME}

      KAFKA_URL: ${KAFKA_URL}
      KAFKA_URL_2: ${KAFKA_URL_2}
    volumes:
      - ./drawing-board-server:/usr/src/app
    env_file:
      - .env
    networks:
      - drawingboard_devnet
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
    restart: always

  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - drawing_board_postgres_data:/var/lib/postgresql/data
    networks: 
      - drawingboard_devnet
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  event-consumers:
    build:
      context: "./event-consumers"
      dockerfile: ./Dockerfile
    container_name: event-consumers
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
    networks:
      - drawingboard_devnet
    volumes:
      - ./event-consumers/src:/app/src


  kafka:
    image: apache/kafka:latest
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - drawingboard_devnet
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CLUSTER_ID=01v8i2YfQguZosUoArIv6A
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - KAFKA_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9093,CONTROLLER://:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9094
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 > /dev/null 2>&1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s


  kafka-init:
    image: apache/kafka:latest
    container_name: kafka-init
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - drawingboard_devnet
    volumes:
      - ./init-scripts/create-topics.dev.sh:/create-topics.dev.sh
    entrypoint: ["/bin/sh", "/create-topics.dev.sh"]

volumes:
  drawing_board_postgres_data:
    driver: local

networks:
  drawingboard_devnet:
    driver: bridge
