services:
  client:
    build:
      context: ./drawing-board-client
      dockerfile: ./Dockerfile.dev
    container_name: client
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_SERVER_URL: ${VITE_SERVER_URL}
    volumes:
      - ./drawing-board-client:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - drawingboard_devnet
    restart: always

  server:
    build:
      context: ./drawing-board-server
      dockerfile: ./Dockerfile.dev
    container_name: server
    ports:
      - "3000:3000"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}

      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}

      CLIENT_URL: ${CLIENT_URL}
      DATABASE_URL: postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_NAME}
    volumes:
      - ./drawing-board-server:/usr/src/app
    networks:
      - drawingboard_devnet
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - drawing_board_postgres_data:/var/lib/postgresql/data
    networks: 
      - drawingboard_devnet
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  event-consumers:
    build:
      context: "./event-consumers"
      dockerfile: ./Dockerfile
    container_name: event-consumers
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
    networks:
      - drawingboard_devnet

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    networks:
      - drawingboard_devnet
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CLUSTER_ID=01v8i2YfQguZosUoArIv6A
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list > /dev/null 2>&1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s


  kafka-2:
    image: apache/kafka:latest
    container_name: kafka-2
    restart: unless-stopped
    ports:
      - "9094:9094"
    networks:
      - drawingboard_devnet
    environment:
      - KAFKA_NODE_ID=2
      - KAFKA_PROCESS_ROLES=broker
      - KAFKA_LISTENERS=PLAINTEXT://:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CLUSTER_ID=01v8i2YfQguZosUoArIv6A
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9094 --list > /dev/null 2>&1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s

  kafka-init:
    image: apache/kafka:latest
    container_name: kafka-init
    depends_on:
      - kafka
      - kafka-2
    networks:
      - drawingboard_devnet
    volumes:
      - ./init-scripts/create-topics.sh:/create-topics.sh
    entrypoint: ["/bin/sh", "/create-topics.sh"]

volumes:
  drawing_board_postgres_data:
    driver: local

networks:
  drawingboard_devnet:
    driver: bridge
